/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;

typedef struct{

        float fPllFreq;

        float fSourceFreq;
        float fSriFreq;
        float fSpbFreq;
        float fCpu0Freq;
        float fCpu1Freq;
        float fCpu2Freq;

        float fFsiFreq;
        float fFsi2Freq;
        float fStmFreq;
        float fGtmFreq;
        float fCanFreq;

} ClockSetting; //클럭 분배 확인을 위한 구조체

int core1_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG1 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
    ClockSetting ClockSettingInfo;

    ClockSettingInfo.fPllFreq=IfxScuCcu_getPllFrequency();
    ClockSettingInfo.fSourceFreq=IfxScuCcu_getSourceFrequency();
    ClockSettingInfo.fSriFreq=IfxScuCcu_getSriFrequency();
    ClockSettingInfo.fSpbFreq=IfxScuCcu_getSpbFrequency();
    ClockSettingInfo.fCpu0Freq=IfxScuCcu_getCpuFrequency(0);
    ClockSettingInfo.fCpu1Freq=IfxScuCcu_getCpuFrequency(1);
    ClockSettingInfo.fCpu2Freq=IfxScuCcu_getCpuFrequency(2);

    ClockSettingInfo.fFsiFreq=IfxScuCcu_getFsiFrequency();
    ClockSettingInfo.fFsi2Freq=IfxScuCcu_getFsi2Frequency();
    ClockSettingInfo.fStmFreq=IfxScuCcu_getStmFrequency();
    ClockSettingInfo.fGtmFreq=IfxScuCcu_getGtmFrequency();
    ClockSettingInfo.fCanFreq=IfxScuCcu_getCanFrequency();

    while(1)
    {
    }
    return (1);
}
