/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/

/***********************************************************************/
/*Include*/
/***********************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "IfxPort.h"
#include "IfxPort_PinMap.h"

//#include "IfxStm.h" //stm모듈!! , stm드라이버에 넣기
//#include "IfxCpu_Irq.h"//stm드라이버에 넣기
#include "Driver_Stm.h" //사용자 정의한 헤더파일이므로 "~~.h"로 추가
//#include "IfxStm.h" //stm모듈!! , stm드라이버에 넣기
//#include "IfxCpu_Irq.h"//stm드라이버에 넣기

/***********************************************************************/
/*Typedef*/
/***********************************************************************/

//typedef struct
//{
 //   Ifx_STM             *stmSfr;            /**< \brief Pointer to Stm register base */
  //  IfxStm_CompareConfig stmConfig;         /**< \brief Stm Configuration structure */
   // volatile uint8       LedBlink;          /**< \brief LED state variable */
    //volatile uint32      counter;           /**< \brief interrupt counter */
//} App_Stm;


/***********************************************************************/
/*Variable 전역변수*/
/***********************************************************************/
//App_Stm g_Stm; /**< \brief Stm global data */
IfxCpu_syncEvent g_cpuSyncEvent = 0;


/***********************************************************************/
/*Static Function Prototype*/
/***********************************************************************/
//void IfxStmDemo_init(void); //선언인데 헤더파일로 들어감

/***********************************************************************/
/*Function*/
/***********************************************************************/
int core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    IfxStmDemo_init(); //stm 모듈 초기화

    /*P00_5    Digital Output*/
    //LED1 켜기
    IfxPort_setPinModeOutput(IfxPort_P00_5.port, IfxPort_P00_5.pinIndex, IfxPort_OutputMode_pushPull, IfxPort_OutputIdx_general);
    IfxPort_setPinLow(IfxPort_P00_5.port, IfxPort_P00_5.pinIndex);

    while(1)
    {

    }
    return (1);
}

//IFX_INTERRUPT(STM_Int0Handler, 0, 100); //ISR 함수를 등록하는 함수
                                        //인수 (isr, vectabNum, prio)
/*
void STM_Int0Handler(void) //인터럽트 핸들러(isr)
{
    static int flag = 0;
    static int cnt = 0;

    IfxStm_clearCompareFlag(g_Stm.stmSfr, g_Stm.stmConfig.comparator);
    //다음 Compare Interrupt가 100,000,000 STM Tick 이후에 발생하도록 하는 것
    IfxStm_increaseCompare(g_Stm.stmSfr, g_Stm.stmConfig.comparator, 100000000u); //새로운 Compare 값 설정


    cnt++;

    if(flag == 0)
    {
        IfxPort_setPinLow(IfxPort_P00_5.port, IfxPort_P00_5.pinIndex);//LED ON
        flag = 1;//바꿔주면서 토글 가능하게 함
    }
    else
    {
        IfxPort_setPinHigh(IfxPort_P00_5.port, IfxPort_P00_5.pinIndex);//LED OFF
        flag = 0;
    }

    IfxCpu_enableInterrupts();
}
*/

