/**********************************************************************************************************************
 * \file Driver_Stm.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/


/***********************************************************************/
/*Include*/
/***********************************************************************/
#include "Driver_Stm.h"
#include "IfxPort.h"
#include "IfxPort_PinMap.h"

/***********************************************************************/
/*Define*/
/***********************************************************************/

/***********************************************************************/
/*Typedef*/
/***********************************************************************/
typedef struct
{
    Ifx_STM             *stmSfr;            /**< \brief Pointer to Stm register base */
    IfxStm_CompareConfig stmConfig;         /**< \brief Stm Configuration structure */
    volatile uint8       LedBlink;          /**< \brief LED state variable */
    volatile uint32      counter;           /**< \brief interrupt counter */
} App_Stm;


/***********************************************************************/
/*Static Function Prototype*/
/***********************************************************************/


/***********************************************************************/
/*Variable*/
/***********************************************************************/
App_Stm g_Stm; /**< \brief Stm global data */


/***********************************************************************/
/*Function*/
/***********************************************************************/
IFX_INTERRUPT(STM_Int0Handler, 0, 100); //ISR 함수를 등록하는 함수
                                        //인수 (isr, vectabNum, prio)

void STM_Int0Handler(void) //인터럽트 핸들러(isr)
{
    static int flag = 0;
    static int cnt = 0;

    IfxStm_clearCompareFlag(g_Stm.stmSfr, g_Stm.stmConfig.comparator);
    //다음 Compare Interrupt가 100,000,000 STM Tick 이후에 발생하도록 하는 것
    IfxStm_increaseCompare(g_Stm.stmSfr, g_Stm.stmConfig.comparator, 100000000u); //새로운 Compare 값 설정


    cnt++;

    if(flag == 0)
    {
        IfxPort_setPinLow(IfxPort_P00_5.port, IfxPort_P00_5.pinIndex);//LED ON
        flag = 1;//바꿔주면서 토글 가능하게 함
    }
    else
    {
        IfxPort_setPinHigh(IfxPort_P00_5.port, IfxPort_P00_5.pinIndex);//LED OFF
        flag = 0;
    }

    IfxCpu_enableInterrupts();
}

void IfxStmDemo_init(void) //stm 모듈 초기화  (정의)
{
    //printf("IfxStmDemo_init() called\n");//추가

    /* disable interrupts */
    boolean interruptState = IfxCpu_disableInterrupts();

    //초기화
   // g_Stm.LedBlink=0;
   // g_Stm.counter=0;

    IfxStm_enableOcdsSuspend(&MODULE_STM0);//우리가 디버거로 멈출때 Timer도 멈추어 달라는 뜻입니다.

    g_Stm.stmSfr = &MODULE_STM0; //STM에 0번 모듈을 사용
    IfxStm_initCompareConfig(&g_Stm.stmConfig); //g_Stm.stmConfig라는 구조체안에 초기화하고 싶은 파라미터를 집어넣는 것

    g_Stm.stmConfig.triggerPriority = 100u; //인터럽트를 발생시키기 위한 우선순위를 집어넣는
                                            //0~255까지 가능하고 255가 우선순위가 가장높음
    g_Stm.stmConfig.typeOfService   = IfxSrc_Tos_cpu0; //인터럽트가 발생할때 이것을 어느 CPU에게 알려주냐
    g_Stm.stmConfig.ticks           = 100000000; //1초(1sec)=10^8 ==>100MHz로 동작하고 있기때문
                                                 //값이 100,000(10^5)이면 1ms
    IfxStm_initCompare(g_Stm.stmSfr, &g_Stm.stmConfig); //ILLD 함수-- 내부적으로 stmConfig.ticks의 1초를 더해줌
    //즉, CMP(비교)레지스터를 업데이트 시켜주는 것

    /* enable interrupts again */
    IfxCpu_restoreInterrupts(interruptState);
}
